name: React.js CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Ensure Dockerfile exists
        run: test -f Dockerfile || { echo "Dockerfile not found"; exit 1; }

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-cicd --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' .

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-cicd:latest
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-cicd:latest

      - name: Delete old container
        run: docker rm -f $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/reactjs-cicd)

      - name: Run Docker container
        run: docker run -d -p 5173:80 --name reactjs-cicd ${{ secrets.DOCKER_USERNAME }}/reactjs-cicd
